In [3]:
import os
from collections import OrderedDict
import torch
import numpy as np

In [1]:
a = [1,2,3,4,5,6,7,8,9,]
b = [7,8,9]
a[-len(b):]

[7, 8, 9]

In [24]:
aa = set(a)
len(aa)

9

In [9]:
np.where([0,0,0,1])[0][0]
np.where([False,False,False,True])[0][0]

3

In [20]:
np.where(np.array(a+[3]) == 3)[0][-1]

9

In [21]:
len([6, 15, 18, 20, 138, 167, 185, 209, 242, 248, 272, 40, 70, 103, 108, 156, 198, 124, 88, 97, 142, 213, 111, 22, 10, 160, 163, 224, 59, 262, 158, 282, 17, 34, 23, 130, 151, 286, 241, 82, 62, 179, 246, 254, 244, 240, 104, 135, 132, 145, 141, 76, 184, 281, 74, 166, 273, 297, 131, 79, 249, 48, 9, 137, 192, 144, 212, 278, 200, 304, 271, 143, 171, 3, 22, 262, 137, 17, 184, 18, 244, 23, 59, 209, 171, 79, 141, 163, 198, 179, 10, 97, 297, 224, 97, 248, 70, 79, 244, 167, 137, 10, 272, 145, 18, 70, 142, 151, 17, 76, 272, 138, 273, 192, 15, 184, 241, 3, 248, 160, 15, 103, 213, 124, 304, 34, 145, 143, 281, 108, 22, 248, 271, 242, 198, 88, 184, 18, 286, 62, 23, 212, 179, 224, 282, 82, 209, 70, 151, 10, 17, 271, 213, 18, 160, 103, 278, 79, 132, 244, 3, 143, 74, 212, 70, 40, 15, 273, 213, 145, 209, 185, 249, 9, 192, 144, 272, 143, 281, 145, 213, 70, 59, 74, 273, 97, 40, 241, 141, 142, 62, 151, 124, 304, 74, 200, 20, 124, 142, 249, 192, 111, 179, 76, 262, 97, 241, 151, 254, 212, 108, 156, 262, 82, 185, 248, 240, 145, 103, 141, 249, 9, 48, 40, 142, 34, 304, 254, 297, 273, 131, 124, 17, 151, 242, 62, 144, 184])

238

In [22]:
len([6, 15, 18, 20, 138, 167, 185, 209, 242, 248, 272, 40, 70, 103, 108, 156, 198, 124, 88, 97, 142, 213, 111, 22, 10, 160, 163, 224, 59, 262, 158, 282, 17, 34, 23, 130, 151, 286, 241, 82, 62, 179, 246, 254, 244, 240, 104, 135, 132, 145, 141, 76, 184, 281, 74, 166, 273, 297, 131, 79, 249, 48, 9, 137, 192, 144, 212, 278, 200, 304, 271, 143, 171, 3, 22, 262, 137, 17, 184, 18, 244, 23, 59, 209, 171, 79, 141, 163, 198, 179, 10, 97, 297, 224, 97, 248, 70, 79, 244, 167, 137, 10, 272, 145, 18, 70, 142, 151, 17, 76, 272, 138, 273, 192, 15, 184, 241, 3, 248, 160, 15, 103, 213, 124, 304, 34, 145, 143, 281, 108, 22, 248, 271, 242, 198, 88, 184, 18, 286, 62, 23, 212, 179, 224, 282, 82, 209, 70, 151, 10, 17, 271, 213, 18, 160, 103, 278, 79, 132, 244, 3, 143, 74, 212, 70, 40, 15, 273, 213, 145, 209, 185, 249, 9, 192, 144, 272, 143, 281, 145, 213, 70, 59, 74, 273, 97, 40, 241, 141, 142, 62, 151, 124, 304, 74, 200, 20, 124, 142, 249, 192, 111, 179, 76, 262, 97, 241, 151, 254, 212, 108, 156, 262, 82, 185, 248, 240, 145, 103, 141, 249, 9, 48, 40, 142, 34, 304, 254, 297, 273, 131, 124, 17, 151, 242, 62, 144, 184, 213, 62, 179, 242, 244, 74, 143, 224, 158, 156, 282, 17, 76, 254, 281, 135, 22, 104, 10, 130, 171, 20, 151, 48, 144, 70, 249, 131, 158, 212, 15, 297, 143, 141, 135, 151, 20, 9, 15, 156, 111, 79, 18, 242, 143, 62, 179, 132, 185, 141, 166, 224, 138, 145, 103, 163, 158, 262, 70, 137, 244, 184, 212, 15, 246, 282, 104, 9, 143, 142, 249, 160, 240, 103, 273, 278, 88, 10, 48, 192, 163, 3, 167, 209, 20, 104, 212, 137, 130, 74, 297, 179, 271, 166, 131, 15, 132, 18, 240, 167, 6, 34, 10, 254, 124, 244, 304, 212, 156, 48, 145, 135, 271, 76, 163, 209, 184, 297, 15, 262, 166, 111, 138, 254, 143, 108, 131, 145, 23, 179, 192, 17, 171, 160, 34, 246, 281, 137, 241, 97, 278, 124])

380

In [17]:
(a+[3]).index(3)

2

In [17]:
def get_gen_token(task):
    if True: #args.add_task_tokens
        return '__' + task + '__'
    else:
        return '__gen__'
TASK_DICT = {
    "movie": {
               "train":os.path.join(args.data_dir,"movie_train.json"),
               "eval":os.path.join(args.data_dir,"movie_dev.json"),
               "test":os.path.join(args.data_dir,"movie_test.json"),
               "n_train_epochs": args.n_train_epochs 
    },
    "boolq": {
               "train":os.path.join(args.data_dir,"boolq_train.json"),
               "eval":os.path.join(args.data_dir,"boolq_dev.json"),
               "test":os.path.join(args.data_dir,"boolq_test.json"),
               "n_train_epochs": args.n_train_epochs 
    },
    "scifact": {
               "train":os.path.join(args.data_dir,"scifact_train.json"),
               "eval":os.path.join(args.data_dir,"scifact_dev.json"),
               "test":os.path.join(args.data_dir,"scifact_test.json"),
               "n_train_epochs": args.n_train_epochs 
    }
}
special_tokens = {"ans_token":'__ans__', "pad_token":'__pad__', "unk_token":'__unk__', "eos_token": '<|endoftext|>'}
    if args.use_sep:
        special_tokens["sep_token"] = '__sep__'

NameError: name 'os' is not defined

In [3]:
task_load = 'boolq'

In [11]:
gen_token = get_gen_token(task_load)
gen_token

'__boolq__'

In [ ]:
#task_id is 0,1,2 (for looped)
# model is the loaded state dict
# first_task is True/False
# to_freeze is the layers to freeze
model = train([task_id], model,first_task,to_freeze)

# Finding Train

In [14]:
arg_tasks = ["boolq", "movie", "scifact"]
task_ids = [0]
tasks = [arg_tasks[task_id] for task_id in task_ids]
tasks

['boolq']

In [ ]:
# getting the data directory of train in the task
train_dataset = [TASK_DICT[t]["train"] for t in tasks]

In [ ]:
# prev_task is the previous task (what if there first??)
# create extra data with the (current task, prev task, model, blank list?)
train_extra_data = []
if "lll" in args.seq_train_type and not args.skip_tasks:
        prev_task = args.tasks[task_ids[0]-1]
        with torch.no_grad():
            create_extra_data(tasks[0], prev_task, model, train_extra_data)

# Finding Create Extra Data

In [ ]:
def create_extra_data(task, prev_task, model, train_extra_data):
    # If Getting Real Samples
    if args.real_sample:
        logger.info(f"using real data as extra data")
        return get_real_data(task, train_extra_data)
    
    
    
    task_cnt = args.tasks.index(task)              # This would be 0 since tasks will have 1 length?
    model_dir = get_model_dir([prev_task])         # Path concat (args.model_dir_root, tasks[0])
    gen_path = os.path.join(model_dir,"lm.csv")    
    if os.path.exists(gen_path):                   # Find if gen_path exists
        logger.info(f"extra data exists in {gen_path}, read it!")
        return read_extra_data(gen_path, train_extra_data) 
    gen_size = DATA_ATTRS[task]["train"]["data_size"]     # a json.load from os.path.join(BASE_DIR,"data_attrs.json"), should be data size
    gen_size = int(np.ceil(gen_size * args.gen_lm_sample_percentage)) # multiply datasize with sample percentage and get ceil
    gen_size -= (gen_size % task_cnt)   #maybe task_cnt not 0?!?! but how?  is this just add? () is negative right?

    if args.debug:
        gen_size = task_cnt

    model.eval()
    logger.info(f"generating extra data!")
    need_process = OrderedDict()
    qa_results = []
    # For a single task_name 'boolq', make qa_results a torch tensor with a single value of the task_name token 
    for task_name in args.tasks[:task_cnt]:
        qa_results.extend([torch.tensor([SPECIAL_TOKEN_IDS[task_name]]) for _ in range(gen_size//task_cnt)])
        
    # Initialize empty tensors for gensize , n_layers ?
    all_pasts = [[
        torch.empty(2, MODEL_CONFIG.n_head, 0, MODEL_CONFIG.n_embd//MODEL_CONFIG.n_head,
            dtype=torch.float if args.fp32 else torch.half).cuda()
        for _ in range(gen_size)
    ] for __ in range(MODEL_CONFIG.n_layer)]
    # a list of max_len in the range of gen_size?
    max_tot_lens = [args.max_len for _ in range(gen_size)]

    # For i in range of gen_size, 
    for i in range(gen_size):
        need_process.update([[i, None]])  # Need_process is an OrderedDict Up Above
        if len(need_process) > int(args.memory_sizes[0] * 0.12): #?!?!? check if len(need_process) > memorysize*12%?
            sample_sequence(model, need_process, qa_results, all_pasts, max_tot_lens)
    sample_sequence(model, need_process, qa_results, all_pasts, max_tot_lens)

    model.train()

    qa_results = [res.tolist() for res in qa_results]
    train_extra_data.extend(qa_results)
    qa_results = [TOKENIZER.decode(res) for res in qa_results]
    
    # Write qa_results as csv, all in gen_path
    write_extra_data(gen_path, qa_results)

In [40]:
qa_results = []
gen_size = 10
task_cnt=1
qa_results.extend([torch.tensor([123]) for _ in range(gen_size//task_cnt)])
qa_results

[tensor([123]),
 tensor([123]),
 tensor([123]),
 tensor([123]),
 tensor([123]),
 tensor([123]),
 tensor([123]),
 tensor([123]),
 tensor([123]),
 tensor([123])]

In [63]:
model_dir_root = "_test_model_knight"
def get_model_dir(tasks):
    return os.path.join(model_dir_root, tasks[0]) 
MODEL_CONFIG = {
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "finetuning_task": None,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 12,
  "n_positions": 1024,
  "num_labels": 1,
  "output_attentions": False,
  "output_hidden_states": False,
  "pruned_heads": {},
  "resid_pdrop": 0.1,
  "summary_activation": None,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": True,
  "summary_type": "cls_index",
  "summary_use_proj": True,
  "task_specific_params": {
    "text-generation": {
      "do_sample": True,
      "max_length": 50
    }
  },
  "torchscript": False,
  "vocab_size": 50261
}


In [127]:
gen_lm_sample_percentage = 0.2

arg_tasks = ["boolq", "movie", "scifact"]
arg_max_len = MODEL_CONFIG["n_positions"]
# gpus = GPUtil.getGPUs()
# gpu_names = [gpus[device_id].name for device_id in args.device_ids]
# if not all(any(turing_arch in gpu_name for turing_arch in TURING_ARCHS) for gpu_name in gpu_names):
#     logger.warning('Not all gpus support fp16 training! Will use fp32 instead.')
#     args.fp32 = True
# if args.model_name == "openai-gpt":
#     args.fp32 = True  # openai-gpt currently doesn't support fp16
# if not args.fp32:
#     global MEMORY_FACTOR
#     MEMORY_FACTOR = dict([k, v*1.4] for k, v in MEMORY_FACTOR.items())
# args.memory_sizes = [gpus[device_id].memoryTotal for device_id in args.device_ids]
# args.memory_sizes[0] = args.memory_sizes[0] * (1 - 0.04 * (args.n_gpus-1))
# for i in range(1, args.n_gpus):
#     args.memory_sizes[i] = args.memory_sizes[i] * 1.04
# if args.train_batch_size <= 0:
#     args.train_batch_size = [int(memory_size * MEMORY_FACTOR[args.seq_train_type]) for memory_size in args.memory_sizes]
# if args.test_batch_size <= 0:
#     args.test_batch_size = [int(memory_size * MEMORY_FACTOR[args.seq_train_type]) for memory_size in args.memory_sizes]
arg_memory_sizes = [100]
model = None
LEN_FACTOR = 1.163
arg_model_name = "gpt2"

task_ids = [0]
tasks = [arg_tasks[task_id] for task_id in task_ids]
prev_task = tasks[task_ids[0]-1]

task = tasks[0]
task_cnt = arg_tasks.index(task)
task_cnt = 1 # TEMP 1?!?

model_dir = get_model_dir([prev_task]) 
gen_path = os.path.join(model_dir,"lm.csv")

gen_size = 6363  # BOOLQ TRAIN DATA SIZE  : DATA_ATTRS[task]["train"]["data_size"]
gen_size = int(np.ceil(gen_size * gen_lm_sample_percentage))
gen_size -= (gen_size % task_cnt) 

print(f"generating extra data!")
need_process = OrderedDict()
qa_results = []
for task_name in arg_tasks[:task_cnt]:
    qa_results.extend([torch.tensor([123]) for _ in range(gen_size//task_cnt)])
all_pasts = [[
    torch.empty(2, MODEL_CONFIG["n_head"], 0, MODEL_CONFIG["n_embd"]//MODEL_CONFIG["n_head"],
        dtype=torch.half).cuda()
    for _ in range(gen_size)
] for __ in range(MODEL_CONFIG["n_layer"])]
max_tot_lens = [arg_max_len for _ in range(gen_size)]

print(f"qa_results length : {len(qa_results)}")
print(qa_results[0:5])
print(f"all_pasts len: {len(all_pasts)}")
print(all_pasts[0][:2])
print(f"max_tot_lens len : {len(max_tot_lens)}")
print(max_tot_lens[:3])

for i in range(gen_size):
    need_process.update([[i, None]])  # Need_process is an OrderedDict Up Above
    if len(need_process) > int(arg_memory_sizes[0] * 0.12): #?!?!? check if len(need_process) > memorysize*12%?
        print(need_process)
        print()
        sample_sequence(model, need_process, qa_results, all_pasts, max_tot_lens, task)
        break

generating extra data!
qa_results length : 1273
[tensor([123]), tensor([123]), tensor([123]), tensor([123]), tensor([123])]
all_pasts len: 12
[tensor([], device='cuda:0', size=(2, 12, 0, 64), dtype=torch.float16), tensor([], device='cuda:0', size=(2, 12, 0, 64), dtype=torch.float16)]
max_tot_lens len : 1273
[1024, 1024, 1024]
OrderedDict([(0, None), (1, None), (2, None), (3, None), (4, None), (5, None), (6, None), (7, None), (8, None), (9, None), (10, None), (11, None), (12, None)])

THIS IS INPUT ID tensor([[123],
        [123],
        [123],
        [123],
        [123],
        [123],
        [123],
        [123],
        [123],
        [123],
        [123],
        [123],
        [123]])
THIS IS cur_id 12
THIS IS batch_ids [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
THIS IS past len 12


TypeError: 'NoneType' object is not callable

In [126]:
def sample_sequence(model, need_process, qa_results, all_pasts, max_tot_lens, task):
    while len(need_process) > 0:
        first_id = next(iter(need_process))             # iterate over need_process, strts with 0
        shortest_len = len(qa_results[first_id])        # qa_results a torch tensor with a single value of the task_name token with length gen
        decode_batch_size = int(arg_memory_sizes[0] * 1.04 // (shortest_len+1)**LEN_FACTOR)
        it = iter(need_process)
        stop = False
        remove_ids = []
        while not stop:
            batch_ids, input_ids, past = [], [], [[] for _ in range(MODEL_CONFIG["n_layer"])]
            while True:
                try:
                    cur_id = next(it)
                    if len(qa_results[cur_id]) > shortest_len:
                        stop = True
                        break
                    batch_ids.append(cur_id)
                    if arg_model_name == "gpt2":
                        input_ids.append(qa_results[cur_id][-1:])  # if gpt2, only put in the last token of the batch_id?
                        for layer_id in range(MODEL_CONFIG["n_layer"]):
                            past[layer_id].append(all_pasts[layer_id][cur_id])
                    else:
                        input_ids.append(qa_results[cur_id])
                    if len(input_ids) == decode_batch_size:
                        break
                except StopIteration:
                    stop = True
                    break
            

            n_inputs = len(input_ids)
            if n_inputs == 0:
                break
            input_ids = torch.stack(input_ids)
            
            print(f"THIS IS INPUT ID {input_ids}")
            print(f"THIS IS batch_ids {batch_ids}")
            print(f"THIS IS past len {len(past)}")
            
            if arg_model_name == "gpt2":
                for layer_id in range(MODEL_CONFIG["n_layer"]):
                    past[layer_id] = torch.stack(past[layer_id], dim=1)
                all_outputs = model(input_ids=input_ids.cuda(), past=past) #somehow gpt2 needs to have past as input too
            else:
                all_outputs = model(input_ids=input_ids.cuda())

            outputs = all_outputs[0]
            if arg_model_name == "gpt2":
                pasts = all_outputs[1] # save all_outputs[1] into pasts

            next_logits = outputs[..., -1, :] / args.temperature_qa
            next_tokens = logits_to_tokens(next_logits).cpu()  # top_k, top_p filtering -> softmax -> multinomial sampling

            for i, cur_id in enumerate(batch_ids):
                if next_tokens[i] == SPECIAL_TOKEN_IDS["eos_token"]:
                    ### KNIGHT ADD POSTPROCESSING ###
                    if qa_results[cur_id][-1] in TOKENIZER.convert_tokens_to_ids(ALLOWED_TOKENS[task]):
                        pass
                    else:
                        qa_results[cur_id][-2] = SPECIAL_TOKEN_IDS["ans_token"]
                        qa_results[cur_id][-1] = TOKENIZER.convert_tokens_to_ids(np.random.choice(ALLOWED_TOKENS[task]))
                    ### END KNIGHT ADD POSTPROCESSING ###
                    remove_ids.append(cur_id)
                else:
                    ### KNIGHT ADD POSTPROCESSING ###
                    if len(qa_results[cur_id])+1 in [max_tot_lens[cur_id], args.max_len]: # CHECK!! is next_tokens really 1 token?!?
                        if next_tokens[i] in TOKENIZER.convert_tokens_to_ids(ALLOWED_TOKENS[task]):
                            pass
                        else:
                            qa_results[cur_id][-1] = SPECIAL_TOKEN_IDS["ans_token"]
                            # or use next_logits
                            
                            next_tokens[i] = TOKENIZER.convert_tokens_to_ids(np.random.choice(ALLOWED_TOKENS[task]))
                            next_tokens[i] = np.max(next_logits.cpu()[TOKENIZER.convert_tokens_to_ids(ALLOWED_TOKENS[task])])
                    ### END KNIGHT ADD POSTPROCESSING ###
                    qa_results[cur_id] = torch.cat((qa_results[cur_id], next_tokens[i])) #append the next_token to the current qa_results
                    if len(qa_results[cur_id]) in [max_tot_lens[cur_id], args.max_len]: # if the length is equal to the max length
                        remove_ids.append(cur_id)                                        # append the batch_id in the remove_ids list
                    elif arg_model_name == "gpt2":
                        for layer_id in range(MODEL_CONFIG.n_layer):
                            all_pasts[layer_id][cur_id] = pasts[layer_id][:, i].type(torch.float if args.fp32 else torch.half)
        
        
        
        for idx in remove_ids:
            remove_id(idx, need_process, all_pasts) # del need_process[idx], all_pasts[layer_id][idx] = 0

In [131]:
np.random.choice(ALLOWED_TOKENS["movies"])

'NEG'

In [129]:
task

'boolq'

In [25]:
gen_size = 201
task_cnt = 1
gen_size -= (gen_size % task_cnt)
gen_size

201

In [130]:
ALLOWED_TOKENS = {
    "movies" : ["NEG", "POS"],
    "boolq": ["True", "False"],
    "scifact": ["REFUTES", "SUPPORTS"]
}

# Finding Sample_sequence

In [31]:
need_process = OrderedDict()
for i in range(10):
    need_process.update([[i, None]])
need_process

OrderedDict([(0, None),
             (1, None),
             (2, None),
             (3, None),
             (4, None),
             (5, None),
             (6, None),
             (7, None),
             (8, None),
             (9, None)])

In [32]:
next(iter(need_process))

0

In [33]:
iter(need_process)

In [ ]:
def sample_sequence(model, need_process, qa_results, all_pasts, max_tot_lens):
    while len(need_process) > 0:
        first_id = next(iter(need_process))             # iterate over need_process, strts with 0
        shortest_len = len(qa_results[first_id])        # qa_results a torch tensor with a single value of the task_name token with length gen
        decode_batch_size = int(args.memory_sizes[0] * MEMORY_FACTOR[args.seq_train_type] // (shortest_len+1)**LEN_FACTOR)
        it = iter(need_process)
        stop = False
        remove_ids = []
        while not stop:
            batch_ids, input_ids, past = [], [], [[] for _ in range(MODEL_CONFIG.n_layer)]
            while True:
                try:
                    cur_id = next(it)
                    if len(qa_results[cur_id]) > shortest_len:
                        stop = True
                        break
                    batch_ids.append(cur_id)
                    if args.model_name == "gpt2":
                        input_ids.append(qa_results[cur_id][-1:])
                        for layer_id in range(MODEL_CONFIG.n_layer):
                            past[layer_id].append(all_pasts[layer_id][cur_id])
                    else:
                        input_ids.append(qa_results[cur_id])
                    if len(input_ids) == decode_batch_size:
                        break
                except StopIteration:
                    stop = True
                    break

            n_inputs = len(input_ids)
            if n_inputs == 0:
                break
            input_ids = torch.stack(input_ids)
            if args.model_name == "gpt2":
                for layer_id in range(MODEL_CONFIG.n_layer):
                    past[layer_id] = torch.stack(past[layer_id], dim=1)
                all_outputs = model(input_ids=input_ids.cuda(), past=past)
            else:
                all_outputs = model(input_ids=input_ids.cuda())

            outputs = all_outputs[0]
            if args.model_name == "gpt2":
                pasts = all_outputs[1]

            next_logits = outputs[..., -1, :] / args.temperature_qa
            next_tokens = logits_to_tokens(next_logits).cpu()

            for i, cur_id in enumerate(batch_ids):
                if next_tokens[i] == SPECIAL_TOKEN_IDS["eos_token"]:
                    remove_ids.append(cur_id)
                else:
                    qa_results[cur_id] = torch.cat((qa_results[cur_id], next_tokens[i]))
                    if len(qa_results[cur_id]) in [max_tot_lens[cur_id], args.max_len]:
                        remove_ids.append(cur_id)
                    elif args.model_name == "gpt2":
                        for layer_id in range(MODEL_CONFIG.n_layer):
                            all_pasts[layer_id][cur_id] = pasts[layer_id][:, i].type(torch.float if args.fp32 else torch.half)
        
        
        
        for idx in remove_ids:
            remove_id(idx, need_process, all_pasts) # del need_process[idx], all_pasts[layer_id][idx] = 0

In [34]:
it = iter(need_process)
batch_ids, input_ids, past = [], [], [[] for _ in range(12)]
while True:
    try:
        cur_id = next(it)                           #cursor_id of need_process??
        if len(qa_results[cur_id]) > shortest_len:  # Check, Stop if qa_results[cur_id] > shortest_len
            stop = True
            break
        batch_ids.append(cur_id)
        if args.model_name == "gpt2":
            input_ids.append(qa_results[cur_id][-1:])         # append input_ids with qa_results[cur_id][-1:]
            for layer_id in range(MODEL_CONFIG.n_layer):       # for all layers
                past[layer_id].append(all_pasts[layer_id][cur_id])     # append past[layer_id] with all_past[Layer_id][cur_id]
        else:
            input_ids.append(qa_results[cur_id])
        if len(input_ids) == decode_batch_size:                # break if len(input_ids) == decode_batch_size
            break
    except StopIteration:
        stop = True
        break

In [35]:
next(iter(need_process))

0